"""add_social_indexes

Revision ID: 1055423e001e
Revises: 9cc859f76472
Create Date: 2026-05-06 21:39:56.521526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1055423e001e'
down_revision: Union[str, Sequence[str], None] = '9cc859f76472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_friendships_created_at'), 'friendships', ['created_at'], unique=False)
    op.create_index(op.f('ix_friendships_follower_id'), 'friendships', ['follower_id'], unique=False)
    op.create_index(op.f('ix_friendships_following_id'), 'friendships', ['following_id'], unique=False)
    op.create_index(op.f('ix_user_activity_created_at'), 'user_activity', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_activity_user_id'), 'user_activity', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_anime_list_anime_id'), 'user_anime_list', ['anime_id'], unique=False)
    op.create_index(op.f('ix_user_anime_list_status'), 'user_anime_list', ['status'], unique=False)
    op.create_index(op.f('ix_user_anime_list_user_id'), 'user_anime_list', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_anime_list_user_id'), table_name='user_anime_list')
    op.drop_index(op.f('ix_user_anime_list_status'), table_name='user_anime_list')
    op.drop_index(op.f('ix_user_anime_list_anime_id'), table_name='user_anime_list')
    op.drop_index(op.f('ix_user_activity_user_id'), table_name='user_activity')
    op.drop_index(op.f('ix_user_activity_created_at'), table_name='user_activity')
    op.drop_index(op.f('ix_friendships_following_id'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_follower_id'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_created_at'), table_name='friendships')
    # ### end Alembic commands ###
