"""Add missing fields to user_anime_list

Revision ID: 7f7d19bba091
Revises: c59343c48c30
Create Date: 2026-05-01 21:01:17.783253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f7d19bba091'
down_revision: Union[str, Sequence[str], None] = 'c59343c48c30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_anime_list', sa.Column('review', sa.Text(), nullable=True))
    op.add_column('user_anime_list', sa.Column('seasons_json', sa.Text(), nullable=True))
    op.add_column('user_anime_list', sa.Column('coop_friend_username', sa.Text(), nullable=True))
    op.add_column('user_anime_list', sa.Column('drop_reason', sa.Text(), nullable=True))
    op.add_column('user_anime_list', sa.Column('custom_tags', sa.Text(), nullable=True))
    op.add_column('user_anime_list', sa.Column('private_notes', sa.Text(), nullable=True))
    op.add_column('user_anime_list', sa.Column('score_story', sa.Float(), nullable=True))
    op.add_column('user_anime_list', sa.Column('score_art', sa.Float(), nullable=True))
    op.add_column('user_anime_list', sa.Column('score_sound', sa.Float(), nullable=True))
    op.add_column('user_anime_list', sa.Column('series_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_anime_list', 'series_name')
    op.drop_column('user_anime_list', 'score_sound')
    op.drop_column('user_anime_list', 'score_art')
    op.drop_column('user_anime_list', 'score_story')
    op.drop_column('user_anime_list', 'private_notes')
    op.drop_column('user_anime_list', 'custom_tags')
    op.drop_column('user_anime_list', 'drop_reason')
    op.drop_column('user_anime_list', 'coop_friend_username')
    op.drop_column('user_anime_list', 'seasons_json')
    op.drop_column('user_anime_list', 'review')
    # ### end Alembic commands ###
