"""initial_schema

Revision ID: 9665bd10df92
Revises: 
Create Date: 2026-05-01 18:00:45.510162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9665bd10df92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('action_text', sa.Text(), nullable=True),
    sa.Column('anime_title', sa.Text(), nullable=True),
    sa.Column('anime_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friends',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('friend_username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('username', 'friend_username')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('anime_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_anime',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('genres', sa.Text(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('seasons_json', sa.Text(), nullable=True),
    sa.Column('coop_friend_username', sa.Text(), nullable=True),
    sa.Column('drop_reason', sa.Text(), nullable=True),
    sa.Column('idMal', sa.Integer(), nullable=True),
    sa.Column('custom_tags', sa.Text(), nullable=True),
    sa.Column('private_notes', sa.Text(), nullable=True),
    sa.Column('score_story', sa.Float(), nullable=True),
    sa.Column('score_art', sa.Float(), nullable=True),
    sa.Column('score_sound', sa.Float(), nullable=True),
    sa.Column('series_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('username', 'anime_id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('theme_url', sa.Text(), nullable=True),
    sa.Column('banner_url', sa.Text(), nullable=True),
    sa.Column('pfp_url', sa.Text(), nullable=True),
    sa.Column('theme_color', sa.String(), nullable=True),
    sa.Column('atmosphere_url', sa.Text(), nullable=True),
    sa.Column('seasonal_theme_enabled', sa.Integer(), nullable=True),
    sa.Column('custom_theme_selection', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('watch_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('anime_id', sa.Integer(), nullable=True),
    sa.Column('episode', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watch_history')
    op.drop_table('users')
    op.drop_table('user_anime')
    op.drop_table('notifications')
    op.drop_table('friends')
    op.drop_table('activity_log')
    # ### end Alembic commands ###
