"""phase1_social_foundation_v2

Revision ID: 9a2a13188fb9
Revises: 7f7d19bba091
Create Date: 2026-05-06 19:28:36.489216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a2a13188fb9'
down_revision: Union[str, Sequence[str], None] = '7f7d19bba091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('follower_id', sa.String(), nullable=False),
    sa.Column('following_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.username'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('activity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_anime')
    op.drop_table('activity_log')
    op.drop_table('friends')
    op.create_foreign_key(None, 'notifications', 'users', ['username'], ['username'], ondelete='CASCADE')
    op.add_column('users', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('timezone', sa.String(), nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.alter_column('watch_history', 'anime_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_foreign_key(None, 'watch_history', 'anime', ['anime_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'watch_history', 'users', ['username'], ['username'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watch_history', type_='foreignkey')
    op.drop_constraint(None, 'watch_history', type_='foreignkey')
    op.alter_column('watch_history', 'anime_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'is_public')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_table('friends',
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('friend_username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('username', 'friend_username', name=op.f('friends_pkey'))
    )
    op.create_table('activity_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('anime_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('anime_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('activity_log_pkey'))
    )
    op.create_table('user_anime',
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('anime_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('episodes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('genres', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('review', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seasons_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('coop_friend_username', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('drop_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('idMal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('custom_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('private_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('score_story', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('score_art', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('score_sound', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('series_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('username', 'anime_id', name=op.f('user_anime_pkey'))
    )
    op.drop_table('user_activity')
    op.drop_table('friendships')
    # ### end Alembic commands ###
