"""Add canonical schema tables JSON

Revision ID: c59343c48c30
Revises: 9665bd10df92
Create Date: 2026-05-01 20:44:48.295142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c59343c48c30'
down_revision: Union[str, Sequence[str], None] = '9665bd10df92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mal_id', sa.Integer(), nullable=True),
    sa.Column('anilist_id', sa.Integer(), nullable=True),
    sa.Column('title_romaji', sa.String(), nullable=True),
    sa.Column('title_english', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('genres', sa.JSON(), nullable=True),
    sa.Column('trailer_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anilist_id'),
    sa.UniqueConstraint('mal_id')
    )
    op.create_table('provider_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('ttl_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_anime_list',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('anime_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('episodes_watched', sa.Integer(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_anime_list')
    op.drop_table('provider_cache')
    op.drop_table('anime')
    # ### end Alembic commands ###
