"""add_forum_models

Revision ID: d65f9f2f3e1c
Revises: f1cb0e1164d0
Create Date: 2026-05-07 00:05:21.845839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65f9f2f3e1c'
down_revision: Union[str, Sequence[str], None] = 'f1cb0e1164d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussion_threads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('anime_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_locked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_spoiler', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_id'], ['users.username'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discussion_threads_anime_id'), 'discussion_threads', ['anime_id'], unique=False)
    op.create_index(op.f('ix_discussion_threads_author_id'), 'discussion_threads', ['author_id'], unique=False)
    op.create_index(op.f('ix_discussion_threads_created_at'), 'discussion_threads', ['created_at'], unique=False)
    op.create_table('discussion_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_spoiler', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.username'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['discussion_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['discussion_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discussion_posts_author_id'), 'discussion_posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_discussion_posts_created_at'), 'discussion_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_discussion_posts_parent_id'), 'discussion_posts', ['parent_id'], unique=False)
    op.create_index(op.f('ix_discussion_posts_thread_id'), 'discussion_posts', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discussion_posts_thread_id'), table_name='discussion_posts')
    op.drop_index(op.f('ix_discussion_posts_parent_id'), table_name='discussion_posts')
    op.drop_index(op.f('ix_discussion_posts_created_at'), table_name='discussion_posts')
    op.drop_index(op.f('ix_discussion_posts_author_id'), table_name='discussion_posts')
    op.drop_table('discussion_posts')
    op.drop_index(op.f('ix_discussion_threads_created_at'), table_name='discussion_threads')
    op.drop_index(op.f('ix_discussion_threads_author_id'), table_name='discussion_threads')
    op.drop_index(op.f('ix_discussion_threads_anime_id'), table_name='discussion_threads')
    op.drop_table('discussion_threads')
    # ### end Alembic commands ###
